@set allusersprofile=c:\programdata
@set appdata=c:\users\lenv\appdata\roaming
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=lenv-pc
@set comspec=c:\windows\system32\cmd.exe
@set devenvdir=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\
@set fp_no_host_check=no
@set framework40version=v4.0
@set frameworkdir=c:\windows\microsoft.net\framework\
@set frameworkdir32=c:\windows\microsoft.net\framework\
@set frameworkversion=v4.0.30319
@set frameworkversion32=v4.0.30319
@set homedrive=c:
@set homepath=\users\lenv
@set include=c:\program files (x86)\microsoft visual studio 14.0\vc\include;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\include;c:\program files (x86)\windows kits\10\include\10.0.10240.0\ucrt;c:\program files (x86)\windows kits\netfxsdk\4.6.1\include\um;c:\program files (x86)\windows kits\8.1\include\\shared;c:\program files (x86)\windows kits\8.1\include\\um;c:\program files (x86)\windows kits\8.1\include\\winrt
@set lib=c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\10\lib\10.0.10240.0\ucrt\x86;c:\program files (x86)\windows kits\netfxsdk\4.6.1\lib\um\x86;c:\program files (x86)\windows kits\8.1\lib\winv6.3\um\x86
@set libpath=c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\lib;c:\program files (x86)\microsoft visual studio 14.0\vc\atlmfc\lib;c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral;\microsoft.vclibs\14.0\references\commonconfiguration\neutral
@set localappdata=c:\users\lenv\appdata\local
@set logonserver=\\lenv-pc
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=c:\program files (x86)\msbuild\sdks
@set msbuild_exe_path=c:\program files (x86)\pvs-studio\buildtools15\msbuild.exe
@set mysqlconnector_assembliespath=c:\program files (x86)\mysql\connector.net 6.9\assemblies\v4.5
@set netfxsdkdir=c:\program files (x86)\windows kits\netfxsdk\4.6.1\
@set number_of_processors=4
@set os=windows_nt
@set path=c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\testwindow;c:\program files (x86)\msbuild\14.0\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\;c:\program files (x86)\microsoft visual studio 14.0\vc\bin;c:\program files (x86)\microsoft visual studio 14.0\common7\tools;c:\windows\microsoft.net\framework\v4.0.30319;c:\program files (x86)\microsoft visual studio 14.0\vc\vcpackages;c:\program files (x86)\html help workshop;c:\program files (x86)\microsoft visual studio 14.0\team tools\performance tools;c:\program files (x86)\windows kits\8.1\bin\x86;c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\;c:\program files (x86)\microsoft visual studio 14.0\common7\ide\commonextensions\microsoft\teamfoundation\team explorer\nativebinaries\x86;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files\tortoisesvn\bin;c:\program files (x86)\xoreax\incredibuild;c:\program files (x86)\windows kits\8.1\windows performance toolkit\;c:\program files\microsoft sql server\120\tools\binn\;c:\program files\mysql\mysql utilities 1.6\;c:\program files\mysql\mysql server 5.7\bin\;c:\users\lenv\appdata\local\programs\python\python36-32;c:\program files\git\cmd;c:\program files\visualsvn server\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc
@set pkgdefapplicationconfigfile=c:\users\lenv\appdata\local\microsoft\visualstudio\14.0\devenv.exe.config
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 94 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=5e03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\;c:\program files\visualsvn server\powershellmodules
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=c:\program files (x86)\msbuild\
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\lenv\appdata\local\temp
@set tmp=c:\users\lenv\appdata\local\temp
@set ucrtversion=10.0.10240.0
@set universalcrtsdkdir=c:\program files (x86)\windows kits\10\
@set userdomain=lenv-pc
@set username=lenv
@set userprofile=c:\users\lenv
@set vcinstalldir=c:\program files (x86)\microsoft visual studio 14.0\vc\
@set visualstudiodir=c:\users\lenv\documents\visual studio 2015
@set visualstudioedition=microsoft visual studio enterprise 2015
@set visualstudioversion=14.0
@set visualsvn_server=c:\program files\visualsvn server\
@set vs100comntools=c:\program files (x86)\microsoft visual studio 10.0\common7\tools\
@set vs140comntools=c:\program files (x86)\microsoft visual studio 14.0\common7\tools\
@set vsinstalldir=c:\program files (x86)\microsoft visual studio 14.0\
@set vslang=2052
@set windir=c:\windows
@set windowslibpath=c:\program files (x86)\windows kits\8.1\references\commonconfiguration\neutral
@set windowssdkdir=c:\program files (x86)\windows kits\8.1\
@set windowssdklibversion=winv6.3\
@set windowssdkversion=\
@set windowssdk_executablepath_x64=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\x64\
@set windowssdk_executablepath_x86=c:\program files (x86)\microsoft sdks\windows\v10.0a\bin\netfx 4.6.1 tools\
@set windows_tracing_flags=3
@set windows_tracing_logfile=c:\bvtbin\tests\installpackage\csilogfile.log

@call cl.exe